server:
  port: 8080
spring:
  freemarker:
    suffix: .ftl
  #    mvc:
  #      view:
  #        prefix: /WEB-INF/jsp/
  #        suffix: .jsp
  #  数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://localhost:3306/datatest?characterEncoding=utf8&serverTimezone=UTC
    username: coolway
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid连接池补充配置
    druid:
      #初始化大小，缺省值0
      initialSize: 5
      #最小连接数（空闲时连接数），缺省值8
      minIdle: 5
      #最大连接数，缺省值8
      maxActive:  50
      #获取连接的等待超时时间，单位：毫秒
      maxWait:  60000
      #打开PSCache，PSCache对支持游标的数据库性能提升巨大，如oracle；mysql下建议关闭，缺省值false
      poolPreparedStatements: false
      #指定每个连接上PSCache的大小，打开PSCache的情况下不能配置负数，尽量配置的大一些，建议100
      maxPoolPreparedStatementPerConnectionSize:  100
      #检测连接是否有效的sql
      validationQuery:  SELECT 1 FROM DUAL
      #检测连接是否有效的等待超时时间，单位：秒
      validationQueryTimeout: 2
      #申请连接时检测连接是否有效，显然会降低性能，缺省值true
      testOnBorrow: false
      #归还连接时检测连接是否有效，显然会降低性能，缺省值false
      testOnReturn: false
      #申请连接时，如果空闲时间>timeBetweenEvictionRunsMillis，则检测连接是否有效，建议配置true
      testWhileIdle:  true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒，缺省值60000
      timeBetweenEvictionRunsMillis:  60000
      #配置一个连接在池中最小生存的时间（空闲而不被驱逐的最小时间），单位：毫秒
      minEvictableIdleTimeMillis: 300000
      #物理连接初始化时执行的sql
      ##      connectionInitSqls:
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，stat监控统计，log4j2日志，wall防御sql注入
      #      filters:  stat,wall,log4j2
      #慢sql监控
      #enabled是否开启慢sql监控；
      #logSlowSql启用监控后，是否打印慢sql;
      #mergeSql是否合并sql（相同sql条件不同的被认为是同一条sql）;
      #slowSqlMillis慢sql的标准
      filter:
        stat:
          enabled:  true
          logSlowSql: true
          mergeSql: true
          slowSqlMillis:  1000
        wall:
          enabled: true
        log4j2:
          enabled: true
      #是否合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat:  true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 1234
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0
    timeout: 10000
    block-when-exhausted: true
druidWebStatFilter:
  enabled:  true



#mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#redis


#test
#一般数据
test:
  testname1: zhangsan
  testname2: "zhang\nsan"
  testname3: 'zhang\nsan'
  #对象
  student:
    name: zhangsan
    age: 20
  #数组
  studentList:
      - name: zhangsan
        age: 20
      - name: lisi
        age: 21
      - name: wangwu
        age: 22
